CREATE PROCEDURE "INCREASE_SALARY_BY_10" (
  "ID" IN NUMBER, 
  "SAL" IN NUMBER) IS

BEGIN  -- Update the employee's salary

	UPDATE EMPLOYEES E SET E.SALARY = SAL+10 WHERE E.EMPLOYEE_ID = ID;

END;
/
