CREATE PROCEDURE "UPDATE_AND_RETURN_SALARY" (
  "ID" IN NUMBER, 
  "SAL" IN NUMBER, 
  "NEW_SALARY" OUT SYS_REFCURSOR) IS

BEGIN -- Update the employee's salary and return new employee name and salary value

	UPDATE EMPLOYEES E SET E.SALARY = SAL WHERE E.EMPLOYEE_ID = ID;
	OPEN NEW_SALARY FOR SELECT FIRST_NAME, SALARY FROM EMPLOYEES WHERE EMPLOYEE_ID = ID;

END;
/
