//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WpfApplication1.Resources.StringResource", typeof(StringResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Авторизуватись.
        /// </summary>
        public static string AutorisationButton {
            get {
                return ResourceManager.GetString("AutorisationButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Відмінити.
        /// </summary>
        public static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Виберіть тип вагону:.
        /// </summary>
        public static string CarriageTypeBox {
            get {
                return ResourceManager.GetString("CarriageTypeBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Плацкарт.
        /// </summary>
        public static string CarrType1 {
            get {
                return ResourceManager.GetString("CarrType1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Купе.
        /// </summary>
        public static string CarrType2 {
            get {
                return ResourceManager.GetString("CarrType2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Люкс.
        /// </summary>
        public static string CarrType3 {
            get {
                return ResourceManager.GetString("CarrType3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Виберіть квиток, який потрібно повернути зі списку:.
        /// </summary>
        public static string ChooseReturnTicketString {
            get {
                return ResourceManager.GetString("ChooseReturnTicketString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Виберіть квиток зі списку для подальшого оформлення квитка:.
        /// </summary>
        public static string ClickToChooseTicket {
            get {
                return ResourceManager.GetString("ClickToChooseTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оформити квиток.
        /// </summary>
        public static string CreateTicketButtonText {
            get {
                return ResourceManager.GetString("CreateTicketButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введіть дані клієнта:.
        /// </summary>
        public static string CreateTicketWelcomeString {
            get {
                return ResourceManager.GetString("CreateTicketWelcomeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введіть дату відправлення (мм.дд.рр.):.
        /// </summary>
        public static string DateBox {
            get {
                return ResourceManager.GetString("DateBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введіть назву станції прибуття:.
        /// </summary>
        public static string EndCityBox {
            get {
                return ResourceManager.GetString("EndCityBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невірний логін чи пароль. Спробуйте ще раз..
        /// </summary>
        public static string InvalidLogin {
            get {
                return ResourceManager.GetString("InvalidLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Логін:.
        /// </summary>
        public static string LoginBox {
            get {
                return ResourceManager.GetString("LoginBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ім&apos;я:.
        /// </summary>
        public static string NameTextBox {
            get {
                return ResourceManager.GetString("NameTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OKButton {
            get {
                return ResourceManager.GetString("OKButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер паспорта:.
        /// </summary>
        public static string PassportTextBox {
            get {
                return ResourceManager.GetString("PassportTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль:.
        /// </summary>
        public static string PasswordBox {
            get {
                return ResourceManager.GetString("PasswordBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Повернути квиток.
        /// </summary>
        public static string ReaturnTicketButton {
            get {
                return ResourceManager.GetString("ReaturnTicketButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Повернути квиток.
        /// </summary>
        public static string ReturnButtonText {
            get {
                return ResourceManager.GetString("ReturnButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введіть прізвище клієнта, який хоче повернути квиток:.
        /// </summary>
        public static string ReturnWelcomeString {
            get {
                return ResourceManager.GetString("ReturnWelcomeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пошук.
        /// </summary>
        public static string SearchButton {
            get {
                return ResourceManager.GetString("SearchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пошук квитка.
        /// </summary>
        public static string SearchTicketButtonText {
            get {
                return ResourceManager.GetString("SearchTicketButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введіть назву станції відправлення:.
        /// </summary>
        public static string StartCityBox {
            get {
                return ResourceManager.GetString("StartCityBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прізвище:.
        /// </summary>
        public static string SurnameTextBox {
            get {
                return ResourceManager.GetString("SurnameTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ласкаво просимо до сервісу з придбання квитків. Виберіть наступні позиції:.
        /// </summary>
        public static string WelcomeString {
            get {
                return ResourceManager.GetString("WelcomeString", resourceCulture);
            }
        }
    }
}
